// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASC6KfQMSRTA0_7Wx4GXME6XeirGETPyM',
    appId: '1:801595423051:web:d042ca84476709a91910ce',
    messagingSenderId: '801595423051',
    projectId: 'ethereal-155c4',
    authDomain: 'ethereal-155c4.firebaseapp.com',
    storageBucket: 'ethereal-155c4.firebasestorage.app',
    measurementId: 'G-TRCEKXQ0G2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA90Kt6JD1LDeaQGirS4w2-o-9N0VoWIc4',
    appId: '1:801595423051:android:d7671afe32ca80741910ce',
    messagingSenderId: '801595423051',
    projectId: 'ethereal-155c4',
    storageBucket: 'ethereal-155c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrDWDWDngmGdU-lVy6pR7css2QPM83j4g',
    appId: '1:801595423051:ios:52434f719b8472791910ce',
    messagingSenderId: '801595423051',
    projectId: 'ethereal-155c4',
    storageBucket: 'ethereal-155c4.firebasestorage.app',
    iosBundleId: 'com.example.ethereal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrDWDWDngmGdU-lVy6pR7css2QPM83j4g',
    appId: '1:801595423051:ios:52434f719b8472791910ce',
    messagingSenderId: '801595423051',
    projectId: 'ethereal-155c4',
    storageBucket: 'ethereal-155c4.firebasestorage.app',
    iosBundleId: 'com.example.ethereal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASC6KfQMSRTA0_7Wx4GXME6XeirGETPyM',
    appId: '1:801595423051:web:dc5ffdbabb7e08fb1910ce',
    messagingSenderId: '801595423051',
    projectId: 'ethereal-155c4',
    authDomain: 'ethereal-155c4.firebaseapp.com',
    storageBucket: 'ethereal-155c4.firebasestorage.app',
    measurementId: 'G-XT41E184J7',
  );

}